language: java
sudo: false # faster builds

services:
  - docker

jdk:
- openjdk8

install: true
cache:
  directories:
  - $HOME/.m2

script:
- ./mvnw verify package

after_success:
- bash <(curl -s https://codecov.io/bash)
